### ISSUE TITLE
Validate client address arg

### ISSUE THREAD

**Issue by melekes** [tendermint/abci#72]
client, err := abciclient.NewClient("127.0.0.1:46657", "socket", true)

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/tendermint/tendermint/vendor/github.com/tendermint/go-common.Connect(0x87bdd3, 0xf, 0x4470ed, 0xc4200b7be8, 0x4470ed, 0x0)
        /home/vagrant/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/go-common/net.go:11 +0xc5
github.com/tendermint/tendermint/vendor/github.com/tendermint/abci/client.(*socketClient).OnStart(0xc4200aefa0, 0x60, 0xc42005e4e0)
        /home/vagrant/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/abci/client/socket_client.go:68 +0x3e
github.com/tendermint/tendermint/vendor/github.com/tendermint/go-common.(*BaseService).Start(0xc4200aefa0, 0x0, 0xc42005e4e0, 0xc420016400)
        /home/vagrant/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/go-common/service.go:96 +0x2c2
github.com/tendermint/tendermint/vendor/github.com/tendermint/abci/client.NewSocketClient(0x87bdd3, 0xf, 0x4af201, 0xa6b4a0, 0xc42000e018, 0xc4200b7ea8)
        /home/vagrant/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/abci/client/socket_client.go:57 +0x23c
github.com/tendermint/tendermint/vendor/github.com/tendermint/abci/client.NewClient(0x87bdd3, 0xf, 0x876c8d, 0x6, 0x1, 0x0, 0xc420011630, 0xc420011600, 0xc420011600)
        /home/vagrant/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/abci/client/client.go:49 +0x17a
main.main()
        /home/vagrant/go/src/github.com/tendermint/tendermint/transacter.go:21 +0x1bf
exit status 2
```

`client, err := abciclient.NewClient("tcp://127.0.0.1:46657", "socket", true)` works.

Return an error?

**Comment by ebuchman** [comment]
:( Yes please

**Comment by adrianbrink** [comment]
Tag: Easy

I think we should tag issues as to their difficulty, since it allows a much easier entry for potential contributors.

**Comment by ebuchman** [comment]
added a test on develop https://github.com/tendermint/abci/commit/4884747eb76608ee799f5d0bf51694c441cf9f62
