### ISSUE TITLE
Cannot assign requested address: JVM_Bind

### ISSUE THREAD

**Issue by rock1103** [tendermint/abci#98]
Hi:
tendermint is installed in my vmware, the vmware ip is 192.168.1.168, JavaCounter demo is in my host computer,I want host computer to connect the vmware,also I modify the TSocket.java code of jabci:
![2](https://user-images.githubusercontent.com/7257681/29445906-d44831b0-841b-11e7-97a7-2f5af1110319.jpg)

but when I run the JavaCounter ,an error occur
starting counter
[Java Counter Main Thread] ERROR com.github.jtendermint.jabci.socket.TSocket - Exception caught when trying to listen on port 46658 or listening for a connection
```
java.net.BindException: Cannot assign requested address: JVM_Bind
	at java.net.DualStackPlainSocketImpl.bind0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketBind(DualStackPlainSocketImpl.java:106)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
	at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:190)
	at java.net.ServerSocket.bind(ServerSocket.java:375)
	at java.net.ServerSocket.<init>(ServerSocket.java:237)
	at com.github.jtendermint.jabci.socket.TSocket.start(TSocket.java:81)
	at com.github.jtendermint.jabci.socket.TSocket.start(TSocket.java:67)
	at java.lang.Thread.run(Thread.java:745)
```
how to solve this issue.
thank you.

**Comment by melekes** [comment]
See https://stackoverflow.com/a/31317721/820520. Make sure the IP address 192.168.1.168 is reachable and points to WMWare instance plus 46658 is open.

```
telnet 192.168.1.168 46658
```

**Comment by zramsay** [comment]
@rock1103 I'm closing this issue as stale. Please re-open if the above fix didn't help.
